-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

game:GetService("ReplicatedStorage").SpinnerWheelRS.Remotes.RequestWheelSpin:FireServer()
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

game:GetService("ReplicatedStorage").SpinnerWheelRS.Remotes.CollectReward:FireServer()